name       : perl-inc-latest
version    : 0.5
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/inc-latest-0.500.tar.gz : daa905f363c6a748deb7c408473870563fcac79b9e3e95b26e130a4a8dc3c611
license    : Apache-2.0
component  : programming.perl
homepage   : https://github.com/dagolden/inc-latest
summary    : inc::latest - use modules bundled in inc/ if they are newer than installed
    ones
description: |
    The "inc::latest" module helps bootstrap configure-time dependencies for
    CPAN distributions. These dependencies get bundled into the "inc"
    directory within a distribution and are used by Makefile.PL or Build.PL.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
